# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mann Robotics
email: BenJetson@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Mann Robotics is a high-school VRC organization
  based in Greenville, South Carolina. We send three
  teams every year to VRC.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
url: "http://bgodfrey.me/bootstrap-testing/"
github_username: mannrobo
repository: benjetson/bootstrap-testing

# Build settings
markdown: kramdown
exclude: 
  - .bundle
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - ATTRIBUTION.md
  - .tests
safe: true
gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji
whitelist:
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji
paginate: 10
paginate_path: "updates/page/:num/"
permalink: "updates/:year/:month/:day/:title/"

# YAML Frontmatter Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      desktopUnCollapse: false
  -
    scope:
      path: "js"
    values:
      layout: null